// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package redis

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e2cfce6DecodeRinhaGolangInternalInfraRedis(in *jlexer.Lexer, out *HealthResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "failing":
			out.Failing = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e2cfce6EncodeRinhaGolangInternalInfraRedis(out *jwriter.Writer, in HealthResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"failing\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Failing))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e2cfce6EncodeRinhaGolangInternalInfraRedis(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e2cfce6EncodeRinhaGolangInternalInfraRedis(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e2cfce6DecodeRinhaGolangInternalInfraRedis(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e2cfce6DecodeRinhaGolangInternalInfraRedis(l, v)
}
