// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package redis

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF48f2bd5DecodeRinhaGolangInternalInfraRedis(in *jlexer.Lexer, out *ReqPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlationId":
			out.CorrelationId = string(in.String())
		case "amount":
			out.Amount = float64(in.Float64())
		case "requestedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.RequestedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF48f2bd5EncodeRinhaGolangInternalInfraRedis(out *jwriter.Writer, in ReqPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlationId\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationId))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"requestedAt\":"
		out.RawString(prefix)
		out.Raw((in.RequestedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReqPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF48f2bd5EncodeRinhaGolangInternalInfraRedis(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReqPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF48f2bd5EncodeRinhaGolangInternalInfraRedis(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReqPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF48f2bd5DecodeRinhaGolangInternalInfraRedis(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReqPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF48f2bd5DecodeRinhaGolangInternalInfraRedis(l, v)
}
